# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a679369ef487fa94aa89b9fa5eccb1556d2ade7f197ea644d0eb0ced73265e9be43faaee98e539e3ddc139099c682c0dd4c09502c7513edc441522fc61c868

test:
  secret_key_base: 9d55f9e00eb1fa822f16709d873e9673eb14c150aacd28d73319cf6ef217867d739f43e205bbcb0bd7078a8eb6eaf7d0daa7cce77296c3368ee5094d6f7cbf3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
